---
- name: ALEX SETUP
  hosts: all
  connection: local
  user: root
  sudo: true

  tasks:

    - name: install EPEL
      yum: name=epel-release state=present

    - name: install the lastest version of blah
      package:
        name: "{{ item }}"
      with_items:
        - "vim"
        - "tmux"
        - "htop"
        - "atop"
        - "sysstat"
        - "git"
        - "subversion"
        - "python"
        - "python-pip"
