---
- name: ALEX SETUP
  hosts: all
  connection: local
  user: root
  become: sudo 

  tasks:

    - name: install EPEL
      yum: name=epel-release state=present
    
  roles:
    - geerlingguy.docker

  #    - name: install the lastest version of blah
  #      package:
  #     name: "{{ item }}"
  #   with_items:
  #     - "vim"
  #     - "tmux"
  #     - "htop"
  #     - "atop"
  #     - "sysstat"
  #     - "git"
  #     - "subversion"
  #     - "python"
  #     - "python-pip"
